config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'posts/myposts'
  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    
         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:user_name, :email, :password)}
    
              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:user_name, :email, :password, :current_password)}
         end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :comment))
        redirect_to post_path(@post), notice: "Comment Created"
    end


    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post), notice: "Comment Deleted"
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :update, :edit, :destroy]
    before_action :authenticate_user!, except: [:index,:show]
    before_action :correct_user, only: [:edit, :update, :destroy]
    
    def index
        @posts = Post.all.order("created_at DESC")
    end
    
    def new
    # @post = Post.new
    @post = current_user.posts.build
    end
    
    def create
        #@post = Post.new(post_params)
        @post = current_user.posts.build(post_params)

        if @post.save
            redirect_to @post, notice: "Post Created"
        else
            render 'new'
        end
    end

    def show
    end

    def update
        if @post.update(post_params)
            redirect_to @post, notice: "Post Updated"
        else
            render 'edit'
        end
    end

    def edit
    end

    def destroy
        @post.destroy
        @comment = @post.comments.where(post_id: @post.id) 
        @comment.each do |comment|
            comment.destroy
        end
        
        redirect_to posts_path, notice: "Post Deleted"
    end

    def correct_user
        @post = current_user.posts.find_by(id: params[:id])
        redirect_to posts_path, notice: "Not Authorised to edit this post" if @post.nil?
    end

    def myposts
        @posts = current_user.posts.all
    end

    private
    
    def post_params
        params.require(:post).permit(:title, :content, :user_id)
    end

    def find_post
        @post = Post.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>:</strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>
     <%= link_to 'Delete', [comment.post, comment],
                  method: :delete, class: "button is-danger is-small", data: { confirm: 'Are you sure?' } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :name, input_html: { class: 'input', autocomplete: "ok" }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
  </div>
</div>
<%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
<% end %>

app/views/layouts/_alert.html.erb
<div class="notification is-info is-light">
  <button class="delete"></button>
    <%= notice %>
</div>

app/views/layouts/_hero.html.erb
<section class="hero is-primary is-small-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Blog', root_path, class: "navbar-item" %>
              <%= link_to 'My Posts', posts_myposts_path, class: "navbar-item" if user_signed_in? %>
              <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <% if user_signed_in? %>
                <%= link_to "New Post", new_post_path, class:"navbar-item" %>
                <%= link_to current_user.user_name, edit_user_registration_path, class:"navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                <% else %>
                <%= link_to "Log In", new_user_session_path, class:"navbar-item" %>
                <%= link_to "Register", new_user_registration_path, class:"navbar-item" %>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'alert' %>
  </head>

  <body>
    <%= render 'layouts/hero' %>
    
    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
    <%= simple_form_for @post do |f| %>
 
    <% if @post.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
            <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>



    <div class="field">
        <div class="control">
            <%= f.input :title, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'}%>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.number_field :user_id ,id: :post_user_id, class:"input" , value: current_user.id, type: :hidden %>
        </div>
    </div>



    <%= f.button :submit, class: 'button is-primary' %>

    <% end %>
</div>

app/views/posts/_posts.html.erb
<div class="section">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"><%= link_to post.title, post  %></p>
              <strong>By: </strong> <%= post.user.user_name %>
            </div>
          </div>
          <div class="content">
            <%= post.content %>
          </div>

          <div class="comment">
           <strong> <%= post.comments.count %> </strong> Comments
            <%= render post.comments %>
          </div>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title,  "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title,  "Index" %>

<%= render 'posts', posts: @posts %>

app/views/posts/myposts.html.erb
<%= render 'posts'%>

app/views/posts/new.html.erb
<% content_for :page_title,  "New Post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title,  @post.title %>

<section class="section">
    <div class="container">
        <nav class="level">
          <!-- Left side -->
          <div class="level-left">
            <p class="level-item">
                <strong>Actions</strong>
            </p>
          </div>
          <!-- Right side -->
          <% if @post.user == current_user %>
          <div class="level-right">
              <p class="level-item">
                <%= link_to "Edit", edit_post_path(@post), class:"button" %>
              </p>
              <p class="level-item">
                <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
            </p>
          </div>
          <% end %>
        </nav>
        <hr/>

        <div class="content">
            <%= @post.content %>
        </div>
    </div>
</section>

<section class="section comments">
    <div class="container">
        <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
        <%= render @post.comments %>
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Leave a reply</h3>
             <%= render 'comments/form' %>
        </div>
    </div>
</section>